'use client'

import React, { useState, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Loader2, Sparkles, AlertCircle, CheckCircle, TrendingUp } from 'lucide-react'

// Mock AI service types (these would be imported from actual AI service)
interface AIResponse {
  text: string
  usage?: {
    promptTokens: number
    completionTokens: number
    totalTokens: number
  }
  model: string
  provider: string
}

interface AIUsage {
  totalRequests: number
  totalTokens: number
  totalCost: number
  remainingRequests: number
  canUseAI: boolean
}

// Mock hooks (these would be actual hooks from the AI module)
const useAIService = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const generateText = useCallback(async (params: {
    prompt: string
    model?: string
    provider?: string
    maxTokens?: number
  }): Promise<AIResponse> => {
    setIsLoading(true)
    setError(null)

    try {
      // Mock API call - in real implementation, this would call the AI service
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      return {
        text: `This is a mock AI response to: "${params.prompt}". In a real implementation, this would be generated by ${params.provider || 'OpenAI'} using the ${params.model || 'gpt-3.5-turbo'} model.`,
        usage: {
          promptTokens: params.prompt.length,
          completionTokens: 50,
          totalTokens: params.prompt.length + 50
        },
        model: params.model || 'gpt-3.5-turbo',
        provider: params.provider || 'openai'
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
      throw err
    } finally {
      setIsLoading(false)
    }
  }, [])

  return { generateText, isLoading, error }
}

const useAIUsageOptimized = () => {
  const [usage, setUsage] = useState<AIUsage>({
    totalRequests: 15,
    totalTokens: 2500,
    totalCost: 0.05,
    remainingRequests: 85,
    canUseAI: true
  })

  return {
    usage,
    canUseAI: usage.canUseAI,
    remainingRequests: usage.remainingRequests,
    updateUsage: (newUsage: Partial<AIUsage>) => {
      setUsage(prev => ({ ...prev, ...newUsage }))
    }
  }
}

// Example Components

export function BasicAIExample() {
  const [prompt, setPrompt] = useState('')
  const [response, setResponse] = useState<AIResponse | null>(null)
  const { generateText, isLoading, error } = useAIService()

  const handleGenerate = async () => {
    if (!prompt.trim()) return

    try {
      const result = await generateText({ prompt })
      setResponse(result)
    } catch (err) {
      console.error('AI generation failed:', err)
    }
  }

  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5" />
          Basic AI Text Generation
        </CardTitle>
        <CardDescription>
          Simple example of AI text generation with basic error handling
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <label htmlFor="prompt" className="text-sm font-medium">
            Enter your prompt:
          </label>
          <Textarea
            id="prompt"
            placeholder="Type your prompt here..."
            value={prompt}
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setPrompt(e.target.value)}
            rows={3}
          />
        </div>

        <Button 
          onClick={handleGenerate} 
          disabled={!prompt.trim() || isLoading}
          className="w-full"
        >
          {isLoading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="mr-2 h-4 w-4" />
              Generate Response
            </>
          )}
        </Button>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {response && (
          <div className="space-y-3">
            <div className="p-4 bg-muted rounded-lg">
              <h4 className="font-medium mb-2">AI Response:</h4>
              <p className="text-sm">{response.text}</p>
            </div>
            
            <div className="flex flex-wrap gap-2">
              <Badge variant="secondary">
                Model: {response.model}
              </Badge>
              <Badge variant="secondary">
                Provider: {response.provider}
              </Badge>
              {response.usage && (
                <Badge variant="outline">
                  Tokens: {response.usage.totalTokens}
                </Badge>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export function UsageTrackingExample() {
  const [prompt, setPrompt] = useState('')
  const [response, setResponse] = useState<AIResponse | null>(null)
  const { generateText, isLoading, error } = useAIService()
  const { usage, canUseAI, remainingRequests, updateUsage } = useAIUsageOptimized()

  const handleGenerate = async () => {
    if (!prompt.trim() || !canUseAI) return

    try {
      const result = await generateText({ prompt })
      setResponse(result)
      
      // Update usage tracking (mock)
      updateUsage({
        totalRequests: usage.totalRequests + 1,
        totalTokens: usage.totalTokens + (result.usage?.totalTokens || 0),
        remainingRequests: Math.max(0, remainingRequests - 1)
      })
    } catch (err) {
      console.error('AI generation failed:', err)
    }
  }

  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <TrendingUp className="h-5 w-5" />
          AI with Usage Tracking
        </CardTitle>
        <CardDescription>
          Example showing AI integration with usage tracking and limits
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Usage Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="text-center p-3 bg-muted rounded-lg">
            <div className="text-2xl font-bold text-primary">{usage.totalRequests}</div>
            <div className="text-xs text-muted-foreground">Total Requests</div>
          </div>
          <div className="text-center p-3 bg-muted rounded-lg">
            <div className="text-2xl font-bold text-primary">{usage.totalTokens}</div>
            <div className="text-xs text-muted-foreground">Total Tokens</div>
          </div>
          <div className="text-center p-3 bg-muted rounded-lg">
            <div className="text-2xl font-bold text-primary">${usage.totalCost.toFixed(3)}</div>
            <div className="text-xs text-muted-foreground">Total Cost</div>
          </div>
          <div className="text-center p-3 bg-muted rounded-lg">
            <div className="text-2xl font-bold text-primary">{remainingRequests}</div>
            <div className="text-xs text-muted-foreground">Remaining</div>
          </div>
        </div>

        {!canUseAI && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              You've reached your AI usage limit. Upgrade your plan to continue using AI features.
            </AlertDescription>
          </Alert>
        )}

        <div className="space-y-2">
          <label htmlFor="prompt-tracked" className="text-sm font-medium">
            Enter your prompt:
          </label>
          <Textarea
            id="prompt-tracked"
            placeholder="Type your prompt here..."
            value={prompt}
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setPrompt(e.target.value)}
            rows={3}
          />
        </div>

        <Button 
          onClick={handleGenerate} 
          disabled={!prompt.trim() || isLoading || !canUseAI}
          className="w-full"
        >
          {isLoading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="mr-2 h-4 w-4" />
              Generate ({remainingRequests} left)
            </>
          )}
        </Button>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {response && (
          <div className="space-y-3">
            <div className="p-4 bg-muted rounded-lg">
              <h4 className="font-medium mb-2">AI Response:</h4>
              <p className="text-sm">{response.text}</p>
            </div>
            
            <div className="flex items-center gap-2">
              <CheckCircle className="h-4 w-4 text-green-600" />
              <span className="text-sm text-muted-foreground">
                Request tracked successfully
              </span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export function AdvancedAIExample() {
  const [prompt, setPrompt] = useState('')
  const [model, setModel] = useState('gpt-3.5-turbo')
  const [provider, setProvider] = useState('openai')
  const [maxTokens, setMaxTokens] = useState('500')
  const [response, setResponse] = useState<AIResponse | null>(null)
  const { generateText, isLoading, error } = useAIService()

  const handleGenerate = async () => {
    if (!prompt.trim()) return

    try {
      const result = await generateText({ 
        prompt,
        model,
        provider,
        maxTokens: parseInt(maxTokens)
      })
      setResponse(result)
    } catch (err) {
      console.error('AI generation failed:', err)
    }
  }

  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5" />
          Advanced AI Configuration
        </CardTitle>
        <CardDescription>
          Example showing advanced AI configuration with multiple providers and models
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="space-y-2">
            <label htmlFor="provider" className="text-sm font-medium">
              Provider:
            </label>
            <Select value={provider} onValueChange={setProvider}>
              <SelectTrigger>
                <SelectValue placeholder="Select provider" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="openai">OpenAI</SelectItem>
                <SelectItem value="anthropic">Anthropic</SelectItem>
                <SelectItem value="google">Google AI</SelectItem>
                <SelectItem value="cohere">Cohere</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label htmlFor="model" className="text-sm font-medium">
              Model:
            </label>
            <Select value={model} onValueChange={setModel}>
              <SelectTrigger>
                <SelectValue placeholder="Select model" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="gpt-3.5-turbo">GPT-3.5 Turbo</SelectItem>
                <SelectItem value="gpt-4">GPT-4</SelectItem>
                <SelectItem value="claude-3-haiku">Claude 3 Haiku</SelectItem>
                <SelectItem value="claude-3-sonnet">Claude 3 Sonnet</SelectItem>
                <SelectItem value="gemini-pro">Gemini Pro</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label htmlFor="maxTokens" className="text-sm font-medium">
              Max Tokens:
            </label>
            <Input
              id="maxTokens"
              type="number"
              value={maxTokens}
              onChange={(e) => setMaxTokens(e.target.value)}
              placeholder="500"
              min="1"
              max="4000"
            />
          </div>
        </div>

        <div className="space-y-2">
          <label htmlFor="advanced-prompt" className="text-sm font-medium">
            Enter your prompt:
          </label>
          <Textarea
            id="advanced-prompt"
            placeholder="Type your detailed prompt here..."
            value={prompt}
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setPrompt(e.target.value)}
            rows={4}
          />
        </div>

        <Button 
          onClick={handleGenerate} 
          disabled={!prompt.trim() || isLoading}
          className="w-full"
        >
          {isLoading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating with {provider}...
            </>
          ) : (
            <>
              <Sparkles className="mr-2 h-4 w-4" />
              Generate with {model}
            </>
          )}
        </Button>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {response && (
          <div className="space-y-3">
            <div className="p-4 bg-muted rounded-lg">
              <h4 className="font-medium mb-2">AI Response:</h4>
              <p className="text-sm">{response.text}</p>
            </div>
            
            <div className="flex flex-wrap gap-2">
              <Badge variant="secondary">
                Provider: {response.provider}
              </Badge>
              <Badge variant="secondary">
                Model: {response.model}
              </Badge>
              {response.usage && (
                <>
                  <Badge variant="outline">
                    Prompt: {response.usage.promptTokens} tokens
                  </Badge>
                  <Badge variant="outline">
                    Completion: {response.usage.completionTokens} tokens
                  </Badge>
                  <Badge variant="outline">
                    Total: {response.usage.totalTokens} tokens
                  </Badge>
                </>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export function AIExamples() {
  return (
    <div className="space-y-8">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold tracking-tight">AI Integration Examples</h2>
        <p className="text-muted-foreground">
          Comprehensive examples of AI service integration with usage tracking and error handling
        </p>
      </div>

      <Tabs defaultValue="basic" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="basic">Basic</TabsTrigger>
          <TabsTrigger value="usage">Usage Tracking</TabsTrigger>
          <TabsTrigger value="advanced">Advanced</TabsTrigger>
        </TabsList>
        
        <TabsContent value="basic" className="space-y-4">
          <BasicAIExample />
        </TabsContent>
        
        <TabsContent value="usage" className="space-y-4">
          <UsageTrackingExample />
        </TabsContent>
        
        <TabsContent value="advanced" className="space-y-4">
          <AdvancedAIExample />
        </TabsContent>
      </Tabs>
    </div>
  )
}

export default AIExamples